version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env  
    environment:
      - MYSQL_ROOT_PASSWORD=123  
      - MYSQL_DATABASE=social_network_db
    ports:
      - "3306:3306"  
    volumes:
      - db:/var/lib/mysql  

  app:
    build: .
    container_name: social_network
    ports:
      - "3334:3334"  
    volumes:
      - .:/usr/app
    depends_on:
      - mysqldb  

volumes:
  db:
    driver: local  
