version: "3.8"

services:
  # app:
  #   build: .
  #   depends_on:
  #     - mysqldb
  #     - redis
  #   ports:
  #     - "3333:3333"

  # mysqldb:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123
  #     - MYSQL_DATABASE=social_network_db
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  db:
