apiVersion: v1
kind: Service
metadata:
  name: social-network-service
spec:
  selector:
    app: social-network
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      nodePort: 30044
  type: NodePort
